categories: [Variant Analysis]
description: A tool to find nonessential, loss-of-function gene variants
name: gnali
owner: nml
long_description: Find and filter nonessential, high-confidence loss-of-function gene variants based on gnomAD.
remote_repository_url: https://github.com/phac-nml/gnali/
homepage_url: https://github.com/phac-nml/gnali/