categories: [Sequence Analysis]
description: SMALT aligns DNA sequencing reads with a reference genome.
long_description: SMALT employs a hash index of short words up to 20 nucleotides long and sampled at equidistant steps along the reference genome. For each sequencing read, potentially matching segments in the reference genome are identified from seed matches in the index and subsequently aligned with the read using dynamic programming.
homepage_url: http://www.sanger.ac.uk/science/tools/smalt-0
remote_repository_url: https://sourceforge.net/projects/smalt/
name:  smalt
owner: nml
